services:
  project-tracker:
    image: project-tracker
    container_name: project-tracker
    build:
      context: .
    ports: 
      - "4200:4200"
    environment:
      - DB_USERNAME=projects
      - DB_PASSWORD=projects
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=projects
      - TZ=Europe/Berlin
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: project-tracker-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projects
      MYSQL_USER: projects
      MYSQL_PASSWORD: projects
    volumes:
      - ./db:/var/lib/mysql
